# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:11.5.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
